"""empty message

Revision ID: d1713ffdbee2
Revises: 
Create Date: 2024-03-18 13:19:05.677685

"""
from alembic import op
import sqlalchemy as sa

from erc20_detector_app.models import CompressedText

# revision identifiers, used by Alembic.
revision = 'd1713ffdbee2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('source_code', CompressedText(), nullable=False),
    sa.Column('is_erc_20', sa.Boolean(), nullable=True),
    sa.Column('erc_20_version', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('WITH_PROCESSING', 'PROCESSING', 'PROCESSED', 'FAILED', name='contractstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Contract')
    # ### end Alembic commands ###
